server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?characterEncoding=utf8&useSSL=false
    username: root
    password: xudusheng
  jpa:
    show-sql: true

logging:
  pattern:
    console: "%d - %msg%n"
